# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0
      
      - name: GitHub Tag
        # You may pin to the exact commit or the version.
        # uses: mathieudutour/github-tag-action@331898d5052eedac9b15fec867b5ba66ebf9b692
        uses: mathieudutour/github-tag-action@v5.5
        with:
          # Required for permission to tag the repo.
          github_token: "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"
          # Which type of bump to use when none explicitly provided (default: `patch`).
          default_bump: minor # optional, default is patch
          # A prefix to the tag name (default: `v`).
          tag_prefix: ""
          # A suffix to a pre-release tag name (default: `<branch>`).
          #append_to_pre_release_tag: # optional
          # Custom tag name. If specified, it overrides bump settings.
          #custom_tag: # optional
          # Comma separated list of release rules. Format: `<keyword>:<release_type>`. Example: `hotfix:patch,pre-feat:preminor`.
          #custom_release_rules: # optional
          # Comma separated list of branches (bash reg exp accepted) that will generate the release tags. Other branches and pull-requests generate versions postfixed with the commit hash and do not generate any tag. Examples: `master` or `.*` or `release.*,hotfix.*,master`...
          #release_branches: # optional, default is master,main
          # Comma separated list of branches (bash reg exp accepted) that will generate pre-release tags.
          #pre_release_branches: # optional
          # Boolean to create an annotated tag rather than lightweight.
          create_annotated_tag: true # optional, default is false
          # Do not perform tagging, just calculate next version and changelog, then exit.
          #dry_run: # optional, default is false
