
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Config
        run: |
          pip install -U git-semver
          git config --global user.email "tiago.matana@gmail.com"
          git config --global user.name "Tiago Matana"
          git fetch --all
          git fetch --tags
      - name: Create Tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |   
          TAG=""
          if [ $(git log -1 --pretty=%B | grep -E ^feature\: | wc -l) -gt 0 ]; then TAG=$(git semver --next-minor); fi
          if [ $(git log -1 --pretty=%B | grep -E ^breaking\: | wc -l) -gt 0 ]; then TAG=$(git semver --next-major); fi
          if [ -z $TAG ]; then TAG=$(git semver --next-patch); fi
          echo "Creating tag: "$TAG
          MSG=$(git log -1 --pretty=%B)
          git tag -a $TAG -m '$MSG'

            
     
        

