
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Release
        # You may pin to the exact commit or the version.
        # uses: elgohr/Github-Release-Action@ed9ebd01a0c57e64e948e7f2ff59c0159e52c204
        uses: elgohr/Github-Release-Action@v3.1
        with:
          # The name of the release to publish
          release: "4.0.1"
      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@526ce12c6675bbe6e0e9a4169c90d09a3f7ad3e2
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          # GitHub secret token
          repo_token: ${{ secrets.TOKEN }} 
          # Git tag (for automatic releases)
          #automatic_release_tag: # optional
          # Should this release be marked as a draft?
          #draft: # optional
          # Should this release be marked as a pre-release?
          #prerelease: # optional, default is true
          # Release title (for automatic releases)
         # title: # optional
          # Assets to upload to the release
         # files: # optional
      - name: Tag
        # You may pin to the exact commit or the version.
        # uses: odinr/action-npm-semver@37020c4b623853993ecaa7dd0f3d99b9ad5f2c2f
        run: |
          git config --global user.email "tiago.matana@gmail.com"
          git config --global user.name "Tiago Matana"
          git fetch --all
          export VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version)
     
        

