# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0
      
      - name: git Tag
        # You may pin to the exact commit or the version.
        # uses: pkg-src/github-action-git-bash@d7e3f57b86fcf5d919a5ba685d459583735b7611
        run: echo $VERSION
      - name: Semantic Version
        # You may pin to the exact commit or the version.
        # uses: ncipollo/semantic-version-action@9fd46cb2499bd4ae1a03b4e95d7f8adf63b1b375
        uses: ncipollo/semantic-version-action@v1
        #with:
          # An optional tag to be used for comparison. If this is omitted the git ref will be used (if it is a tag).
          #tag: # optional, default is 
        
        
   
