
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Tag
        # You may pin to the exact commit or the version.
        # uses: odinr/action-npm-semver@37020c4b623853993ecaa7dd0f3d99b9ad5f2c2f
        run: |
          git config --global user.email "tiago.matana@gmail.com"
          git config --global user.name "Tiago Matana"
          git fetch --all
          git fetch --tags origin
          export TAG=''
          pip install git-semver
          if [ $(git log -1 --pretty=%B | grep -E ^feature\: | wc -l) -gt 0 ]; then export TAG=$(git semver --next-minor); fi
          if [ $(git log -1 --pretty=%B | grep -E ^breaking\: | wc -l) -gt 0 ]; then export TAG=$(git semver --next-major); fi
          if [ -z $TAG ]; then export TAG=$(git semver --next-patch); fi
          git tag -a $TAG -m $(git log -1 --pretty=%B)
     
        

