
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Config
        run: |
          pip install -U git-semver
          git config --global user.email "tiago.matana@gmail.com"
          git config --global user.name "Tiago Matana"
          git fetch --all
          git fetch --tags
      - name: Create Tag
        # You may pin to the exact commit or the version.
        # uses: odinr/action-npm-semver@37020c4b623853993ecaa7dd0f3d99b9ad5f2c2f
        run: |   
          VERSION=$(./git-version.sh)
          MSG=$(git log -1 --pretty=%B)
          git tag -a $VERSION -m '$MSG'
          git push --tags
      - name: Create Release
        run: |
          git config --global github.token ${{ secrets.TOKEN }}
          ./git-release.sh $VERSION $MSG
     
        

